### ISSUE TITLE
Code about SUN RGB-D.

### ISSUE THREAD

**Issue by zyrant** [gwenzhang/GGA#1]
hi, 

Do you plan to release the code for the SUN RGB-D?

best wishes.

**Comment by gwenzhang** [comment]
Thanks for your interest. I will release the SUN-RGBD code later.

**Comment by linQian99** [comment]
Thank you for your reply! May I also ask the gpu requirements for training this program? Thank you for your time

> Thanks for your interest. I will release the SUN-RGBD code later.

**Comment by gwenzhang** [comment]
> Thank you for your reply! May I also ask the gpu requirements for training this program? Thank you for your time

I take 2 A100/A40 for training CenterPoint for the KITTI dataset with 12 hours. I also try to use 8 A40 and it will take about 4 hours.

**Comment by wb014** [comment]
> Thanks for your interest. I will release the SUN-RGBD code later.

Hi, 

Thank you for your work on this project. I am very interested in exploring it further. I was wondering if there are any plans to release the SUN-RGBD code soon. It would be really helpful.

Thank you for your time and consideration!
